# Generated by Django 4.0.5 on 2022-06-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
