# Generated by Django 4.0.5 on 2022-07-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='numero',
            field=models.Field(),
        ),
    ]
